### ISSUE TITLE
Fast does not work

### ISSUE THREAD

**Issue by guyluz11** [0xdir/lifi-api-dart#3]
When adding fast option to the request the package returns error 

Code
```dart
  await client.setState(
    Selector.id('myDeviceId'),
    power: "on",
    fast: true,
  );
```

Error

```
Closure: (Object, StackTrace) => dynamic from Function 'error': static.
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
#3      JsonDecoder.convert (dart:convert/json.dart:610:36)
#4      JsonCodec.decode (dart:convert/json.dart:216:41)
#5      jsonDecode (dart:convert/json.dart:155:10)
#6      new SetStateResponse (package:lifx_http_api/src/client/responses/set_state_response.dart:13:36)
#7      LIFXClient.setState (package:lifx_http_api/src/client/lifx_client.dart:76:11)
<asynchronous suspension>
#8      main (file:///home/guyluz/Documents/git/lifx_http_api/example/main.dart:12:3)
<asynchronous suspension>
```

**Comment by guyluz11** [comment]
I think it is new that jsonEncode input is only Map<String, String> and not Map<String, dynamic>

In 
lib/src/client/lifx_client.dart:72 we are doing `body: jsonEncode(body),` but `fast` input is bool and not string.
So it crashes there

**Comment by 0xdir** [comment]
I believe you have posted on the wrong package repo. The package you should be raising the issue to is: https://pub.dev/packages/lifx_http_api

**Comment by guyluz11** [comment]
Hoo you are right, thank you
